name: ${project.name}
author: Bradley Steele (Ibiza)
description: ${project.description}
version: ${project.version}
main: me.bradleysteele.timedrewards.TimedRewards
depend: [BCommons]
api-version: 1.13